name: Get Last Commit ID

on:
  push:
    branches:
      - master  # Adjust branch name as needed

jobs:
  get_last_commit_id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Get last commit ID
        id: last_commit
        run: echo "::set-output name=commit_id::$(git log -1 --pretty=format:%H)"
      
      - name: Print last commit ID
        run: |
          echo "Last commit ID: ${{ steps.last_commit.outputs.commit_id }}"

      - name: Download properties file from GitHub Packages
        run: |
            mkdir -p $HOME/.m2
            echo "//npm.pkg.github.com/:_authToken=${{secrets.TOKEN}}" > $HOME/.m2/settings.xml
            mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:get -DremoteRepositories=https://maven.pkg.github.com/sachin-smartbear/project_ready -Dartifact=org.example:project_ready:1.1

      - name: Extract commit ID from properties file
        id: extract_commit_id
        run: |
          COMMIT_ID=$(grep 'git.commit.id.full' some.properties | cut -d'=' -f2)
          echo "::set-output name=commit_id::$COMMIT_ID"

      - name: Use the extracted commit ID
        run: |
          echo "Commit ID is ${{ steps.extract_commit_id.outputs.commit_id }}"